[
package
]
name = "crystal-nature-simulation"
version = "0.1.0"
edition = "2021"

[
dependencies
]
winit = "0.28"
env_logger = "0.10"
log = "0.4"
wgpu = "0.16"
pollster = "0.3"
bytemuck = { version = "1.13", features = ["derive"] }
rand = "0.8"

[
build-dependencies
]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"
